### PR TITLE
Fix annotated #123

### PR DESCRIPTION
**Pull request by hodgespodge**
This should fix issue #123 

This changes get_type_hints(f, include_extras=True) to use the "include_extras" flag which does _not_ remove annotated typing information. Also, cleans up some inconsistency with typing vs typing_extensions to support annotated in py 38

### CODE REVIEW

**Comment by wesselb** [comment]
Hey @hodgespodge! By closing the PR, do you mean that you would not like to go through with it?

**Comment by hodgespodge** [comment]
Howdy @wesselb,

Sorry about the confusion and thanks for checking. I would like to go through with the PR. I had initially second guessed some of my changes but I think they're probably fine. I'll reopen the PR as a draft since there are a few more things I want to double check. In the mean time, if anything problematic stands out, please let me know!

Also, I wasn't able to run some of the benchmarking tests locally but I assume that probably isn't a big issue.

**Comment by wesselb** [comment]
@hodgespodge Not a problem at all. :) The PR looks pretty good to me, assuming that everything works as expected!

**Comment by hodgespodge** [comment]
@wesselb Alrighty this PR is ready for review

**Comment by wesselb** [comment]
@hodgespodge I think this looks great! Some very minor formatting check is failing, but I'll fix that myself. I'll resolve the conflict with `plum/signature.py`, merge this, and tag a new release right away. :)

**Pull request merged**
