### PR TITLE
Handle C-defined classes (jax.jit) in methodTable repr

### PR DESCRIPTION
**Pull request by PhilipVinc**
Turns out that classes defined in C (such as the wrapper classes returned by `jax.jit` &co) raise an error when passed to `inspect.gefile`, and we were not handling that type of error.

This PR fixes it, by handling that error and actually finding the proper module when relevant.

I'm not sure how to test this, as I don't know how to easily define a class from C... but you can see what it was before and now

testing.py
```python
python-3.11.4 ❯ cat testing.py
from plum import dispatch
import jax

@dispatch
@jax.jit
def fun(a: int, b: int):
	return a * b
```

now 
```python
~/Dropbox/Ricerca/Codes/Python/plum pv/repr*
python-3.11.4 ❯ ipython -c "import testing; print(testing.fun.methods)"
List of 1 method(s):
    [0] fun(a: int, b: int)
        <PjitFunction of <function fun at 0x1037bf380>> @ ~/Dropbox/Ricerca/Codes/Python/plum/testing.py:4
```

before
```python
~/Dropbox/Ricerca/Codes/Python/plum master* ⇡
python-3.11.4 ❯ ipython -c "import testing; print(testing.fun.methods)"
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 import testing; print(testing.fun.methods)

File ~/Dropbox/Ricerca/Codes/Python/plum/plum/repr.py:135, in __repr_from_rich__(self)
    133 console = rich.get_console()
    134 with console.capture() as capture:
--> 135     console.print(self, end="")
    136 res = capture.get()
    137 return res

File ~/Documents/pythonenvs/plum-dev/python-3.11.4/lib/python3.11/site-packages/rich/console.py:1490, in Console.print(self, sep, end, style, justify, overflow, no_wrap, emoji, markup, highlight, width, height, crop, soft_wrap, *objects)
   1488 if style is None:
   1489     for renderable in renderables:
-> 1490         extend(render(renderable, render_options))
   1491 else:
   1492     for renderable in renderables:

File ~/Documents/pythonenvs/plum-dev/python-3.11.4/lib/python3.11/site-packages/rich/console.py:1132, in Console.render(self, renderable, options)
   1128     raise errors.NotRenderableError(
   1129         f"object {render_iterable!r} is not renderable"
   1130     )
   1131 _Segment = Segment
-> 1132 for render_output in iter_render:
   1133     if isinstance(render_output, _Segment):
   1134         yield render_output

File ~/Dropbox/Ricerca/Codes/Python/plum/plum/method.py:166, in MethodList.__rich_console__(self, console, options)
    164 for i, method in enumerate(self):
    165     method_repr = method.__rich_console__(console, options)
--> 166     yield Padding(sum(method_repr, Text(f"[{i}] ")), (0, 4))

File ~/Dropbox/Ricerca/Codes/Python/plum/plum/method.py:93, in Method.__rich_console__(self, console, options)
     92 def __rich_console__(self, console, options):
---> 93     yield self.repr_mismatch()

File ~/Dropbox/Ricerca/Codes/Python/plum/plum/method.py:153, in Method.repr_mismatch(self, mismatches, varargs_matched)
    150     res.append(f"\n    precedence={sig.precedence}")
    152 res.append("\n    ")
--> 153 res.append_text(repr_pyfunction(self.implementation))
    155 return res

File ~/Dropbox/Ricerca/Codes/Python/plum/plum/repr.py:115, in repr_pyfunction(f)
    105 """Create a :class:`rich.Text` object representation a function, including a link
    106 to the source definition created with :func:`repr_source_path`.
    107
   (...)
    112     :class:`rich.Text`: Representation of `f`.
    113 """
    114 res = Text(repr(f))
--> 115 source = repr_source_path(f)
    116 if source is not None:
    117     res.append(" @ ")

File ~/Dropbox/Ricerca/Codes/Python/plum/plum/repr.py:82, in repr_source_path(function)
     71 """Create a :class:`rich.Text` object with an hyperlink to the function definition.
     72
     73 Args:
   (...)
     79         it returns :obj:`None`.
     80 """
     81 try:
---> 82     f_path = inspect.getfile(function)
     83     f_line = inspect.getsourcelines(function)[1]
     84     uri = f"file://{f_path}#{f_line}"

File ~/.pyenv/versions/3.11.4/lib/python3.11/inspect.py:920, in getfile(object)
    918 if iscode(object):
    919     return object.co_filename
--> 920 raise TypeError('module, class, method, function, traceback, frame, or '
    921                 'code object was expected, got {}'.format(
    922                 type(object).__name__))

TypeError: module, class, method, function, traceback, frame, or code object was expected, got PjitFunction

~/Dropbox/Ricerca/Codes/Python/plum master* ⇡
python-3.11.4 ❯
``

### CODE REVIEW

**Comment by nstarman** [comment]
@PhilipVinc @wesselb, it would be super useful to have some small section of the docs recommending best practices for JIT + dispatch.  JIT tracing through and compiling away the dispatch means we can see large performance gains. It would be fantastic to have an explanation / demonstration of this.

**Comment by PhilipVinc** [comment]
Problem is, that's not really 'supported' because if you use dispatch inside a jax.jit function, the function gets jitted, and if you now redefine the dispatch logic jax has no idea he has to recompile...

Properly supporting this is not easy, though it would be possible.

This PR here is to work with the opposite paradigm: dispatching on jax.jitted functions...

Though, I agree with you that everything should be documented..

**Comment by PhilipVinc** [comment]
@wesselb if you have a minute, would you be willing to quickly tell me if this is good for you? It's just for the `repr` of `.methods` when we have jax.jitted functions.

I'd love if this could make it for the next release.

**Comment by wesselb** [comment]
@PhilipVinc Yep! Just quickly grabbing some food and will review, merge, and release this right afterwards.

**Comment by wesselb** [comment]
Looks great to me! Merging this right away. I'll see if I can find a way to test it. I'll first release version.

@nstarman The idea of eliminating overhead coming from dispatch by using a JIT is very powerful. It's been one of the key ideas in the design of some other packages that build on Plum, e.g. [LAB](https://github.com/wesselb/lab) and [Stheno](https://github.com/wesselb/stheno). I wrote a blog post a while back with [a practical example of this idea](https://wessel.ai/2021/01/19/linear-models-with-stheno-and-jax.html#making-inference-fast), which shows a massive performance gain.

**Comment by wesselb** [comment]
@PhilipVinc This is included in `v2.4.1`!

**Pull request merged**
