### PR TITLE
refactor: small cleanup

### PR DESCRIPTION
**Pull request by nstarman**
Slowly adding typing.
This would be good to combine with #147.

### CODE REVIEW

**Comment by wesselb** [comment]
Thanks again for the PR, @nstarman! This change looks good to me.

One question about this: What’s the benefit of making Dispatcher a dataclass c.f. a normal class? Is it that you can set `slots`, presumably for a performance boost?

**Comment by PhilipVinc** [comment]
Slots means a tiny bit less overhead memory. But that does not impact anything we do because that’s sort of a singleton.

I like data classes when they can help make the codec more clear , but in general they are a pain to work with because you lose control over __init__ …

‘I’m not sure it’s the best idea to use them here. Though in that particular case it won’t hurt either. But it can add friction for future refactors

**Comment by nstarman** [comment]
> Slots means a tiny bit less overhead memory. But that does not impact anything we do because that’s sort of a singleton.

Only here. `Dispatcher` is part of the public API and other libraries create their own instances.

> I  like data classes when they can help make the codec more clear , but in general they are a pain to work with because you lose control over init …

They reduce boilerplace, add introspection and interop tools (e.g. `replace`), and they don't relinquish control over `__init__` (if an `__init__` is defined on a class, not a superclass, `@dataclass` will not rewrite it).

**Comment by wesselb** [comment]
Thanks for the discussion, both! Since it’s a fairly small change and comes with some benefits (albeit minor ones), I think it’s worthwhile trying to make Dispatcher a dataclass. Should we later decide that we don’t like it after all, because it could make future changes more difficult as @PhilipVinc points out, it would be easy to make Dispatcher a normal class again. Will merge right away! :) Thanks again, @nstarman!

**Pull request merged**
